-- =========================================================
-- SCHEMA CORRIGE — installation initiale (partie 02)
-- Upgrades ultérieurs : doc/sql/README.md (ex. BCrypt partie 05)
-- Corrections apportées par rapport à l'original :
--  1. Sens des FK inversé -> remis dans le bon sens (enfant -> parent)
--  2. "type" TYPE -> "type" "type" (référence correcte à l'enum)
--  3. PK composite (id, type) sur médias -> PK(id) seul
--  4. FK articles -> articles_medias dupliquée -> supprimée
--  5. Colonnes article_id/articles_id sur catégories et médias laissées
--     NULLables car redondantes avec les tables de jonction (N-N)
-- =========================================================

DROP TABLE IF EXISTS "articles_medias" CASCADE;
DROP TABLE IF EXISTS "articles_categories" CASCADE;
DROP TABLE IF EXISTS "catégories" CASCADE;
DROP TABLE IF EXISTS "médias" CASCADE;
DROP TABLE IF EXISTS "commentaires" CASCADE;
DROP TABLE IF EXISTS "articles" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TYPE IF EXISTS "type";

CREATE TYPE "type" AS ENUM (
    'image',
    'video',
    'gif',
    'musique'
);

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "pseudo" VARCHAR(255),
    "mail" VARCHAR(255),
    "mdp" VARCHAR(255),
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "articles" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "titre" VARCHAR(255),
    "contenu" TEXT,
    "date" TIMESTAMP,
    "statut" BOOLEAN,
    "update" TIMESTAMP,
    "user_id" INTEGER,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "commentaires" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contenu" TEXT,
    "user_id" INTEGER,
    "article_id" INTEGER,
    "date" TIMESTAMP,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "médias" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" "type",
    "url" VARCHAR(255),
    "articles_id" INTEGER, -- redondant avec articles_medias, laissé NULL dans le seed
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "catégories" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nom" VARCHAR(255),
    "description" VARCHAR(255),
    "article_id" INTEGER, -- redondant avec articles_categories, laissé NULL dans le seed
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "articles_categories" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "article_id" INTEGER,
    "categorie_id" INTEGER,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "articles_medias" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "media_id" INTEGER,
    "article_id" INTEGER,
    PRIMARY KEY("id")
);

-- FK dans le bon sens : la table enfant référence la table parent
ALTER TABLE "articles"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "commentaires"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "commentaires"
    ADD FOREIGN KEY("article_id") REFERENCES "articles"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "médias"
    ADD FOREIGN KEY("articles_id") REFERENCES "articles"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "catégories"
    ADD FOREIGN KEY("article_id") REFERENCES "articles"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "articles_categories"
    ADD FOREIGN KEY("article_id") REFERENCES "articles"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "articles_categories"
    ADD FOREIGN KEY("categorie_id") REFERENCES "catégories"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "articles_medias"
    ADD FOREIGN KEY("article_id") REFERENCES "articles"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "articles_medias"
    ADD FOREIGN KEY("media_id") REFERENCES "médias"("id")
    ON UPDATE NO ACTION ON DELETE NO ACTION;


-- =========================================================
-- DONNEES DE TEST (SEED)
-- Toutes les données ci-dessous sont fictives, générées pour
-- le test. Les mots de passe sont des placeholders en clair
-- pour la démo -- en production il faut les hasher (bcrypt/argon2),
-- ne jamais stocker de mdp en clair.
-- =========================================================

-- 10 utilisateurs
INSERT INTO "users" ("id", "pseudo", "mail", "mdp") VALUES
(1, 'alice_dev',    'alice@example.com',    'hash_placeholder_1'),
(2, 'bob_martin',   'bob@example.com',      'hash_placeholder_2'),
(3, 'clara_lyon',   'clara@example.com',    'hash_placeholder_3'),
(4, 'david_k',      'david@example.com',    'hash_placeholder_4'),
(5, 'elsa_p',       'elsa@example.com',     'hash_placeholder_5'),
(6, 'fabien_r',     'fabien@example.com',   'hash_placeholder_6'),
(7, 'gaelle_t',     'gaelle@example.com',   'hash_placeholder_7'),
(8, 'hugo_b',       'hugo@example.com',     'hash_placeholder_8'),
(9, 'ines_m',       'ines@example.com',     'hash_placeholder_9'),
(10,'julien_v',     'julien@example.com',   'hash_placeholder_10');

-- 12 articles répartis entre les users
INSERT INTO "articles" ("id", "titre", "contenu", "date", "statut", "update", "user_id") VALUES
(1,  'Les bases du SQL',                 'Contenu de démonstration sur les fondamentaux du SQL...',            '2026-01-05 10:00:00', TRUE,  '2026-01-05 10:00:00', 1),
(2,  'Introduction à PostgreSQL',        'Contenu de démonstration sur PostgreSQL...',                          '2026-01-10 09:30:00', TRUE,  '2026-01-11 14:00:00', 1),
(3,  'Modéliser une base avec Merise',   'Contenu de démonstration sur MCD/MLD...',                             '2026-01-12 11:15:00', TRUE,  '2026-01-12 11:15:00', 2),
(4,  'JavaScript pour débutants',        'Contenu de démonstration sur les bases JS...',                        '2026-01-15 08:00:00', TRUE,  '2026-01-16 09:00:00', 3),
(5,  'Comprendre les API REST',          'Contenu de démonstration sur REST...',                                '2026-01-18 13:45:00', FALSE, '2026-01-18 13:45:00', 3),
(6,  'Spring Boot en pratique',          'Contenu de démonstration sur Spring Boot...',                         '2026-01-20 10:20:00', TRUE,  '2026-01-21 10:20:00', 4),
(7,  'Le rugby et les stats sportives',  'Contenu de démonstration éditorial rugby...',                         '2026-02-01 07:30:00', TRUE,  '2026-02-01 07:30:00', 5),
(8,  'Gérer une copropriété',            'Contenu de démonstration sur la gestion de syndic...',                '2026-02-03 16:00:00', TRUE,  '2026-02-03 16:00:00', 5),
(9,  'PHP moderne',                      'Contenu de démonstration sur PHP 8...',                               '2026-02-05 12:00:00', TRUE,  '2026-02-06 08:00:00', 6),
(10, 'Le hi-fi vintage',                 'Contenu de démonstration sur les platines vinyles...',                '2026-02-08 18:00:00', FALSE, '2026-02-08 18:00:00', 7),
(11, 'Percussions du monde',             'Contenu de démonstration sur l''histoire des percussions...',        '2026-02-10 09:00:00', TRUE,  '2026-02-10 09:00:00', 8),
(12, 'Automatiser avec n8n',             'Contenu de démonstration sur l''automatisation...',                   '2026-02-12 15:30:00', TRUE,  '2026-02-13 10:00:00', 9);

-- Commentaires
INSERT INTO "commentaires" ("id", "contenu", "user_id", "article_id", "date") VALUES
(1,  'Super article, merci !',                    2,  1,  '2026-01-05 12:00:00'),
(2,  'Ça manque un peu d''exemples je trouve.',    3,  1,  '2026-01-05 15:00:00'),
(3,  'Très clair, bravo.',                         4,  2,  '2026-01-11 09:00:00'),
(4,  'J''aurais aimé un schéma en plus.',          5,  3,  '2026-01-12 18:00:00'),
(5,  'Merci pour cette intro !',                   1,  4,  '2026-01-16 10:00:00'),
(6,  'Est-ce que ça marche avec Express aussi ?',  6,  5,  '2026-01-19 08:30:00'),
(7,  'Bon résumé de Spring Boot.',                 7,  6,  '2026-01-21 11:00:00'),
(8,  'Intéressant, je ne connaissais pas ces stats.', 8, 7,  '2026-02-01 09:15:00'),
(9,  'Ça correspond exactement à ma situation.',   9,  8,  '2026-02-03 17:00:00'),
(10, 'PHP 8 a vraiment progressé.',                10, 9,  '2026-02-06 09:00:00'),
(11, 'J''ai une platine similaire !',              2,  10, '2026-02-08 19:00:00'),
(12, 'Passionnant, merci pour ce partage.',        3,  11, '2026-02-10 10:30:00'),
(13, 'n8n est top pour ce genre de use-case.',     4,  12, '2026-02-13 08:00:00'),
(14, 'Petite coquille dans le paragraphe 2.',      5,  1,  '2026-01-06 10:00:00'),
(15, 'Vivement la suite !',                        6,  2,  '2026-01-12 07:00:00'),
(16, 'Je vais tester ça ce week-end.',             7,  3,  '2026-01-13 20:00:00'),
(17, 'Bonne synthèse.',                            8,  4,  '2026-01-17 12:00:00'),
(18, 'Merci, ça répond à ma question.',            9,  5,  '2026-01-20 09:00:00'),
(19, 'Article bien structuré.',                    10, 6,  '2026-01-22 14:00:00'),
(20, 'Hâte du prochain article rugby.',            1,  7,  '2026-02-02 08:00:00');

-- 5 catégories
INSERT INTO "catégories" ("id", "nom", "description") VALUES
(1, 'Développement',   'Articles techniques sur la programmation'),
(2, 'Base de données', 'Articles sur SQL, modélisation, ORM'),
(3, 'Lifestyle',       'Articles hors-tech (hi-fi, musique, rugby...)'),
(4, 'Gestion & Business', 'Articles sur la gestion de projet, syndic, etc.'),
(5, 'Automatisation',  'Articles sur les outils no-code / automatisation');

-- 10 médias
INSERT INTO "médias" ("id", "type", "url") VALUES
(1,  'image',   'https://cdn.example.com/img/sql-basics.jpg'),
(2,  'image',   'https://cdn.example.com/img/postgres-logo.jpg'),
(3,  'video',   'https://cdn.example.com/video/merise-explained.mp4'),
(4,  'gif',     'https://cdn.example.com/gif/js-loop.gif'),
(5,  'image',   'https://cdn.example.com/img/rest-api-diagram.jpg'),
(6,  'video',   'https://cdn.example.com/video/spring-boot-demo.mp4'),
(7,  'image',   'https://cdn.example.com/img/rugby-stats.jpg'),
(8,  'image',   'https://cdn.example.com/img/copro-meeting.jpg'),
(9,  'musique', 'https://cdn.example.com/audio/vinyl-sample.mp3'),
(10, 'image',   'https://cdn.example.com/img/n8n-workflow.jpg');

-- Liaison articles <-> catégories (N-N)
INSERT INTO "articles_categories" ("id", "article_id", "categorie_id") VALUES
(1,  1,  1),
(2,  1,  2),
(3,  2,  2),
(4,  3,  2),
(5,  4,  1),
(6,  5,  1),
(7,  6,  1),
(8,  7,  3),
(9,  8,  4),
(10, 9,  1),
(11, 10, 3),
(12, 11, 3),
(13, 12, 5),
(14, 12, 1);

-- Liaison articles <-> médias (N-N)
INSERT INTO "articles_medias" ("id", "media_id", "article_id") VALUES
(1,  1,  1),
(2,  2,  2),
(3,  3,  3),
(4,  4,  4),
(5,  5,  5),
(6,  6,  6),
(7,  7,  7),
(8,  8,  8),
(9,  9,  10),
(10, 10, 12);

-- Réajustement des séquences IDENTITY pour éviter les collisions
-- si tu ajoutes des lignes après ce script
SELECT setval(pg_get_serial_sequence('"users"', 'id'), (SELECT MAX("id") FROM "users"));
SELECT setval(pg_get_serial_sequence('"articles"', 'id'), (SELECT MAX("id") FROM "articles"));
SELECT setval(pg_get_serial_sequence('"commentaires"', 'id'), (SELECT MAX("id") FROM "commentaires"));
SELECT setval(pg_get_serial_sequence('"catégories"', 'id'), (SELECT MAX("id") FROM "catégories"));
SELECT setval(pg_get_serial_sequence('"médias"', 'id'), (SELECT MAX("id") FROM "médias"));
SELECT setval(pg_get_serial_sequence('"articles_categories"', 'id'), (SELECT MAX("id") FROM "articles_categories"));
SELECT setval(pg_get_serial_sequence('"articles_medias"', 'id'), (SELECT MAX("id") FROM "articles_medias"));